[tox]
isolated_build = true
envlist = py{310,311,312,313,314}-test,lint,pylint

[testenv]
allowlist_externals =
    python3
    poetry
    pytest
deps =
    poetry
    pytest
commands =
    python3 -m poetry install --no-root --with dev
    python3 -m pytest -p no:ruff -vvv --cov --cov-append --cov-report term --cov-report xml {posargs}
    # python3 -m poetry run pytest -p no:ruff -vvv --cov --cov-append --cov-report term --cov-report xml {posargs}
    # for logging "-o log_cli=true -o log_cli_level=debug"
[testenv:lint]
allowlist_externals = ruff
description = lint source code
deps =
    ruff
commands =
    ruff check ollama_proxy_server tests
    ruff format --check --line-length 180 ollama_proxy_server tests

[testenv:pylint]
whitelist_externals =
    python3
    pylint
deps =
    pylint
commands =
    python3 -m pylint -j 4 --score=n --output-format=colorized --ignore=tests --rcfile={toxinidir}/tox.ini ollama_proxy_server
#    sh -c ' \
#        find . -iname "*.py" | grep -v ".tox" | xargs -n 1 -P 3 pylint \
#        --score=n \
#        --output-format=colorized \
#        --ignore=tests \
#        --rcfile={toxinidir}/tox.ini \
#        '
[pylint]
never-returning-functions=sys.exit
max-line-length=180
max-module-lines=5000
max-nested-blocks=10
min-public-methods=1
max-public-methods=20
max-statements=200
max-branches=50
max-locals=75
max-args=10
notes=
    FIXME,
    XXX,
    TODO
disable=
    broad-except,
#    import-error,
#    unused-argument,
#    import-outside-toplevel,
#    raise-missing-from,
#    super-with-arguments,
#    use-maxsplit-arg,
#    consider-using-f-string

[coverage:run]
omit =
    tests/*
