---
name: build wheel

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:

  build-wheel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Set up the cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: cache-python-packages

      - name: Set up the project
        run: |
          pip install poetry
          # poetry config virtualenvs.in-project true

      # build for all versions of python ?
      - name: build
        run: poetry build

      - name: Archive build and wheel
        uses: actions/upload-artifact@v4
        with:
          name: build-and-wheel
          path: dist
